frp-server:
  management:
    port: 8089
  tunnels:
    - name: 测试
      open-port: 8082
      agent-port: 8083

quarkus:
  http:
    port: ${frp-server.management.port}
  log:
    category:
      "net.ximatai":
        level: DEBUG

    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) Line:%L - %s%e%n"
    file:
      enable: true
      path: logs/frp-server.log
      level: DEBUG
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) Line:%L - %s%e%n"
      rotation:
        file-suffix: .yyyy-MM-dd
        rotate-on-boot: true
        max-backup-index: 7
