name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]  # 新增标签触发条件
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test with Gradle
        run: ./gradlew test

  # 新增发布任务（仅在打标签时运行）
  release:
    needs: check  # 依赖检查任务先通过
    if: startsWith(github.ref, 'refs/tags/v')  # 标签过滤
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 构建UberJAR
      - name: Build UberJARs
        run: |
          ./gradlew :frp-server:build -Dquarkus.package.jar.type=uber-jar
          ./gradlew :frp-agent:build -Dquarkus.package.jar.type=uber-jar

      # 定位生成的JAR文件
      - name: Find Artifacts
        id: find-artifacts
        run: |
          echo "server_jar=$(find frp-server/build -name '*-runner.jar')" >> $GITHUB_OUTPUT
          echo "agent_jar=$(find frp-agent/build -name '*-runner.jar')" >> $GITHUB_OUTPUT

      # 创建Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.find-artifacts.outputs.server_jar }}
            ${{ steps.find-artifacts.outputs.agent_jar }}
          generate_release_notes: true
